name: Test if branch exists
on:
  workflow_dispatch:
jobs:
  check_branch_exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check branch exists
        run: |
          UPDATE_SNAPSHOT_BRANCH_NAME="hj/test_branch"
          local existed_in_remote=$(git ls-remote --heads origin $UPDATE_SNAPSHOT_BRANCH_NAME)
            if [[ -z ${existed_in_remote} ]]; then
              echo 0
            else
              echo 1
            fi